export const _CLOSE_DIALOG = "CLOSE_DIALOG";
export const _OPEN_ADDRESS_DIALOG = "OPEN_ADDRESS_DIALOG";
export const _OPEN_PHONE_DIALOG = "OPEN_PHONE_DIALOG";
export const _OPEN_NEW_BOOK_DIALOG = "OPEN_NEW_BOOK_DIALOG";
export const _OPEN_NEW_PROFILE_IMAGE_DIALOG = "OPEN_NEW_PROFILE_IMAGE_DIALOG";
